version: 2.1

jobs:
  build:
    docker:
      - image: oven/bun:1.2.13
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bun install --frozen-lockfile
      - run:
          name: Test
          command: bun run test
      - run:
          name: test coverage
          command: bun run test:coverage
      - run:
          name: check coverage
          command: bun run test:coverage:check
      - run:
          name: Build
          command: bun run build

workflows:
  backend-ci:
    jobs:
      - build